// Generated by CoffeeScript 1.12.4
var emailRe, middleware;

emailRe = /^[a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/;

middleware = {
  isRequired: function(value) {
    if (value && value !== '') {
      return value;
    }
    throw new Error('Required');
  },
  isEmail: function(value) {
    if (!value) {
      return value;
    }
    if (emailRe.test(value)) {
      return value.toLowerCase();
    }
    throw new Error('Enter a valid email');
  },
  isPassword: function(value) {
    if (!value) {
      throw new Error('Required');
    }
    if (value.length >= 6) {
      return value;
    }
    throw new Error('Password must be atleast 6 characters long');
  }
};

module.exports = middleware;

//# sourceMappingURL=index.js.map
