// Generated by CoffeeScript 1.12.4
module.exports = {
  Controls: require('./controls'),
  Graphics: require('./graphics'),
  List: require('./list'),
  ListItem: require('./list-item'),
  CommandBar: require('./command-bar'),
  Dynamic: require('./dynamic'),
  Login: require('./login'),
  Main: require('./main'),
  Menu: require('./menu'),
  register: function() {
    this.Controls.register();
    this.Graphics.register();
    this.List.register();
    this.ListItem.register();
    this.CommandBar.register();
    this.Login.register();
    this.Main.register();
    return this.Menu.register();
  }
};

//# sourceMappingURL=index.js.map
