// Generated by CoffeeScript 1.12.4
var CrowdControl, Menu,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

CrowdControl = require('crowdcontrol');

module.exports = Menu = (function(superClass) {
  extend(Menu, superClass);

  function Menu() {
    return Menu.__super__.constructor.apply(this, arguments);
  }

  Menu.prototype.tag = 'daisho-menu';

  Menu.prototype.html = require('../templates/menu');

  Menu.prototype.error = null;

  Menu.prototype.init = function() {
    return Menu.__super__.init.apply(this, arguments);
  };

  Menu.prototype.items = function() {
    var items, k, ref, v;
    items = [];
    ref = this.services.menu.menu;
    for (k in ref) {
      v = ref[k];
      items.push({
        name: k,
        onclick: v
      });
    }
    return items;
  };

  return Menu;

})(CrowdControl.Views.View);

//# sourceMappingURL=menu.js.map
