// Generated by CoffeeScript 1.12.4
var MenuService;

module.exports = MenuService = (function() {
  MenuService.prototype.menu = null;

  MenuService.prototype.initFn = null;

  MenuService.prototype.daisho = null;

  MenuService.prototype.debug = false;

  function MenuService(daisho, debug) {
    this.daisho = daisho;
    this.debug = debug;
    this.menu = {};
  }

  MenuService.prototype.register = function(name, fn) {
    if (this.menu[name]) {
      console.log('---MENU SERVICE---\nCollision for ' + name);
    }
    this.menu[name] = fn;
    if (this.initFn == null) {
      return this.initFn = fn;
    }
  };

  MenuService.prototype.run = function(name) {
    var fn;
    fn = this.menu[name];
    if (!fn && this.debug) {
      console.log('---MENU SERVICE---\n' + name + ' not registered');
    }
    return fn();
  };

  MenuService.prototype.start = function() {
    if (!this.initFn && this.debug) {
      console.log('---MENU SERVICE---\nnothing registered');
      return;
    }
    return this.initFn();
  };

  return MenuService;

})();

//# sourceMappingURL=menu.js.map
