// Generated by CoffeeScript 1.12.4
var PageService;

module.exports = PageService = (function() {
  PageService.prototype.cache = null;

  PageService.prototype.daisho = null;

  PageService.prototype.debug = false;

  PageService.prototype.current = null;

  function PageService(daisho, debug) {
    this.daisho = daisho;
    this.debug = debug;
    this.cache = {};
  }

  PageService.prototype.mount = function() {};

  PageService.prototype.update = function() {};

  PageService.prototype.register = function(id, enterFn, startFn, stopFn) {
    if (this.cache[id]) {
      console.log('---PAGE SERVICE---\nCollision for ' + id);
    }
    return this.cache[id] = {
      id: id,
      enter: enterFn,
      start: startFn,
      stop: stopFn,
      root: null
    };
  };

  PageService.prototype.show = function(id) {
    var page;
    page = this.cache[id];
    if (page == null) {
      console.log('---PAGE SERVICE---\n' + id + ' not registered');
    }
    if (this.current != null) {
      page.root = this.current.stop(this);
    }
    if (!page.root) {
      page.root = page.enter(this);
      page.root = page.start(this);
      if (this.debug) {
        console.log('---PAGE SERVICE---\nDone serving page ' + id);
      }
    } else {
      page.root = page.start(this);
      if (this.debug) {
        console.log('---PAGE SERVICE---\nDone serving page ' + id);
      }
    }
    this.current = page.root;
    return this.current;
  };

  return PageService;

})();

//# sourceMappingURL=page.js.map
