// Generated by CoffeeScript 1.12.4
module.exports = {
  Checkbox: require('./checkbox'),
  DateRangePicker: require('./date-range-picker'),
  Password: require('./password'),
  Select: require('./select'),
  SelectCountry: require('./select-country'),
  SelectState: require('./select-state'),
  Text: require('./text'),
  TextArea: require('./textarea'),
  register: function() {
    this.Checkbox.register();
    this.DateRangePicker.register();
    this.Password.register();
    this.Select.register();
    this.SelectCountry.register();
    this.SelectState.register();
    this.Text.register();
    return this.TextArea.register();
  }
};

//# sourceMappingURL=index.js.map
