// Generated by CoffeeScript 1.12.4
var Select, SelectCountry, countries,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Select = require('./select');

countries = require('../../data/countries');

module.exports = SelectCountry = (function(superClass) {
  extend(SelectCountry, superClass);

  function SelectCountry() {
    return SelectCountry.__super__.constructor.apply(this, arguments);
  }

  SelectCountry.prototype.tag = 'select-country-control';

  SelectCountry.prototype.options = function() {
    return countries.data;
  };

  SelectCountry.prototype.lookup = 'country';

  SelectCountry.prototype.init = function() {
    SelectCountry.__super__.init.apply(this, arguments);
    return this.on('update', (function(_this) {
      return function() {
        var country, k, ref, v;
        country = _this.input.ref.get(_this.lookup);
        if (country) {
          country = country.toLowerCase();
          if (country.length === 2) {
            return _this.input.ref.set(_this.lookup, country);
          } else {
            ref = countries.data;
            for (k in ref) {
              v = ref[k];
              if (v.toLowerCase() === country) {
                _this.input.ref.set(_this.lookup, k);
                return;
              }
            }
          }
        }
      };
    })(this));
  };

  return SelectCountry;

})(Select);

//# sourceMappingURL=select-country.js.map
