// Generated by CoffeeScript 1.12.4
var Text, TextArea,
  extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

Text = require('./text');

module.exports = TextArea = (function(superClass) {
  extend(TextArea, superClass);

  function TextArea() {
    return TextArea.__super__.constructor.apply(this, arguments);
  }

  TextArea.prototype.tag = 'textarea-control';

  TextArea.prototype.html = require('../../templates/controls/textarea');

  TextArea.prototype.formElement = 'textarea';

  return TextArea;

})(Text);

//# sourceMappingURL=textarea.js.map
