// Generated by CoffeeScript 1.12.4
module.exports = {
  Change: 'daisho.change',
  ChangeSuccess: 'daisho.change.success',
  ChangeFailed: 'daisho.change.failed',
  Login: 'daisho.login',
  LoginSuccess: 'daisho.login.success',
  LoginFailed: 'daisho.login.failed',
  Logout: 'daisho.logout',
  Refresh: 'daisho.refresh',
  ForceRefresh: 'daisho.refresh.force'
};

//# sourceMappingURL=events.js.map
