// Generated by CoffeeScript 1.12.4
module.exports = {
  Model: require('./model'),
  Chart: require('./chart'),
  Counter: require('./counter'),
  register: function() {
    this.Chart.register();
    return this.Counter.register();
  }
};

//# sourceMappingURL=index.js.map
