// Generated by CoffeeScript 1.12.4
module.exports = {
  "new": function() {
    return [this.newSeries()];
  },
  newSeries: function() {
    return {
      series: '',
      type: 'line',
      xs: [],
      ys: [],
      fmt: {
        x: function(n) {
          return n;
        },
        y: function(n) {
          return n;
        }
      },
      tip: {
        x: function(n) {
          return n;
        },
        y: function(n) {
          return n;
        }
      },
      axis: {
        x: {
          name: '',
          fmt: function(n) {
            return n;
          },
          scale: null,
          ticks: function(n) {
            return n;
          }
        },
        y: {
          name: '',
          fmt: function(n) {
            return n;
          },
          scale: null,
          ticks: function(n) {
            return n;
          }
        }
      }
    };
  }
};

//# sourceMappingURL=model.js.map
